import './globals.css';
import { Inter } from 'next/font/google';
import AuthState from './context/auth/authState';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'React - NodeSend',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <AuthState>{children}</AuthState>
      </body>
    </html>
  );
}
